//------------------------------------------------------------------------
// Copyright(c) 2024 Noah Dominic Miranda Silvio.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"NSimpleCrusher.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"NSimpleCrusher VST3 (64Bit)"
#else
#define stringFileDescription	"NSimpleCrusher VST3"
#endif
#define stringCompanyName		"Noah Dominic Miranda Silvio\0"
#define stringLegalCopyright	"Copyright(c) 2024 Noah Dominic Miranda Silvio."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
